### ISSUE TITLE
Fix wrong certificate for https://cryptecs.eu

### ISSUE THREAD

**Issue by iko4** [cryptecs/cryptecs.github.io#11]
It seems like some misconfiguration happened when addressing issue #5.
The website serves the wrong certificate when trying to access https://cryptecs.eu (without the `www` subdomain) and I get errors like the following.
> Firefox does not trust this site because it uses a certificate that is not valid for cryptecs.eu. The certificate is only valid for the following names: *.github.com, www.github.com, github.io, github.com, *.github.io, githubusercontent.com, *.githubusercontent.com

**Comment by strieflin** [comment]
Hm. That didn't happen when I tested after the reconfiguration. Needs some investigation.

**Comment by iko4** [comment]
This seems fixed for me now. Do you want to check/investigate more?

**Comment by strieflin** [comment]
Thank you for verifying @iko4. Will close this now.
