### ISSUE TITLE
Fix wrong certificate

### ISSUE THREAD

**Issue by iko4** [cryptecs/cryptecs.github.io#16]
The website seems to serve the wrong certificate. For example, Firefox shows the following error.
> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.cryptecs.eu. The certificate is only valid for the following names: *.github.io, github.io, *.github.com, github.com, www.github.com, *.githubusercontent.com, githubusercontent.com
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

This is the same error as in #11 but it happens for https://www.cryptecs.eu/ now (https://cryptecs.eu/ gets redirected to https://www.cryptecs.eu/ and produces the same error).

**Comment by strieflin** [comment]
This was a DNS hickup. Has been resolved now.
