### ISSUE TITLE
Serve the website also via the apex domain

### ISSUE THREAD

**Issue by iko4** [cryptecs/cryptecs.github.io#5]
Currently, the only custom domain configured to serve the website seems to be the `www` subdomain (`www.cryptecs.eu`).
To simplify accessing the website by manually typing the URL and to avoid the potential for sharing the wrong URL (e.g. on the [profile page][cryptecs-profile] or the [export control page][cryptecs-export-control]), you should consider to configure [GitHub to serve the website via the apex domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages) (`cryptecs.eu`).

[cryptecs-profile]: https://github.com/cryptecs/.github/blob/master/profile/README.md
[cryptecs-export-control]: https://github.com/cryptecs/cryptecs.github.io/blob/master/docs/legal/export-control.md

**Comment by strieflin** [comment]
I have configured our DNS provider to support the APEX domain.
